version: "1.0"
info:
  model: int-scaffold
packages:
- name: SourabhProject
  gitServerName: sourabhProject
  gitUrl: https://github.com/souhSAG/SourabhProject
  gitUsername: souhSAG
  gitBranch: main
services:
- serviceName: project.sourabh.integrations:helloworld
  packages:
  - name: SourabhProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
